package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Action generated by hbm2java
 */
public class Action  implements java.io.Serializable {


     private Integer idAction;
     private String libelleAction;
     private Set<Role> roles = new HashSet<Role>(0);

    public Action() {
    }

    public Action(String libelleAction, Set<Role> roles) {
       this.libelleAction = libelleAction;
       this.roles = roles;
    }
   
    public Integer getIdAction() {
        return this.idAction;
    }
    
    public void setIdAction(Integer idAction) {
        this.idAction = idAction;
    }
    public String getLibelleAction() {
        return this.libelleAction;
    }
    
    public void setLibelleAction(String libelleAction) {
        this.libelleAction = libelleAction;
    }
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }




}


