package metier;
// Generated 20 f�vr. 2018 21:49:57 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Action generated by hbm2java
 */
public class Action implements java.io.Serializable {

    private Integer idAction;
    private String libelleAction;
    private Set<Role> roles = new HashSet<Role>(0);

    public Action() {
    }

    public Action(String libelleAction, Set<Role> roles) {
        this.libelleAction = libelleAction;
        this.roles = roles;
    }

    public Integer getIdAction() {
        return this.idAction;
    }

    public void setIdAction(Integer idAction) {
        this.idAction = idAction;
    }

    public String getLibelleAction() {
        return this.libelleAction;
    }

    public void setLibelleAction(String libelleAction) {
        this.libelleAction = libelleAction;
    }

    public Set<Role> getRoles() {
        return this.roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.getIdAction());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Action other = (Action) obj;
        if (!Objects.equals(this.getIdAction(), other.getIdAction())) {
            return false;
        }
        return true;
    }

}
