package metier;
// Generated 20 f�vr. 2018 21:49:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Categorieexercice generated by hbm2java
 */
public class Categorieexercice  implements java.io.Serializable {


     private Integer idCategorieExercice;
     private String libelleCategorieExercice;
     private Set<Exercice> exercices = new HashSet<Exercice>(0);

    public Categorieexercice() {
    }

    public Categorieexercice(String libelleCategorieExercice, Set<Exercice> exercices) {
       this.libelleCategorieExercice = libelleCategorieExercice;
       this.exercices = exercices;
    }
   
    public Integer getIdCategorieExercice() {
        return this.idCategorieExercice;
    }
    
    public void setIdCategorieExercice(Integer idCategorieExercice) {
        this.idCategorieExercice = idCategorieExercice;
    }
    public String getLibelleCategorieExercice() {
        return this.libelleCategorieExercice;
    }
    
    public void setLibelleCategorieExercice(String libelleCategorieExercice) {
        this.libelleCategorieExercice = libelleCategorieExercice;
    }
    public Set<Exercice> getExercices() {
        return this.exercices;
    }
    
    public void setExercices(Set<Exercice> exercices) {
        this.exercices = exercices;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 19 * hash + Objects.hashCode(this.getIdCategorieExercice());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Categorieexercice other = (Categorieexercice) obj;
        if (!Objects.equals(this.getIdCategorieExercice(), other.getIdCategorieExercice())) {
            return false;
        }
        return true;
    }




}


