package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorieexercice generated by hbm2java
 */
public class Categorieexercice  implements java.io.Serializable {


     private Integer idCategorieExercice;
     private String libelleCategorieExercice;
     private Set<Exercice> exercices = new HashSet<Exercice>(0);

    public Categorieexercice() {
    }

    public Categorieexercice(String libelleCategorieExercice, Set<Exercice> exercices) {
       this.libelleCategorieExercice = libelleCategorieExercice;
       this.exercices = exercices;
    }
   
    public Integer getIdCategorieExercice() {
        return this.idCategorieExercice;
    }
    
    public void setIdCategorieExercice(Integer idCategorieExercice) {
        this.idCategorieExercice = idCategorieExercice;
    }
    public String getLibelleCategorieExercice() {
        return this.libelleCategorieExercice;
    }
    
    public void setLibelleCategorieExercice(String libelleCategorieExercice) {
        this.libelleCategorieExercice = libelleCategorieExercice;
    }
    public Set<Exercice> getExercices() {
        return this.exercices;
    }
    
    public void setExercices(Set<Exercice> exercices) {
        this.exercices = exercices;
    }




}


