package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Coach generated by hbm2java
 */
public class Coach  implements java.io.Serializable {


     private Integer idCoach;
     private String nomCoach;
     private String prenomCoach;
     private String mailCoach;
     private Set<Communiquer> communiquers = new HashSet<Communiquer>(0);
     private Set<Client> clients = new HashSet<Client>(0);

    public Coach() {
    }

    public Coach(String nomCoach, String prenomCoach, String mailCoach, Set<Communiquer> communiquers, Set<Client> clients) {
       this.nomCoach = nomCoach;
       this.prenomCoach = prenomCoach;
       this.mailCoach = mailCoach;
       this.communiquers = communiquers;
       this.clients = clients;
    }
   
    public Integer getIdCoach() {
        return this.idCoach;
    }
    
    public void setIdCoach(Integer idCoach) {
        this.idCoach = idCoach;
    }
    public String getNomCoach() {
        return this.nomCoach;
    }
    
    public void setNomCoach(String nomCoach) {
        this.nomCoach = nomCoach;
    }
    public String getPrenomCoach() {
        return this.prenomCoach;
    }
    
    public void setPrenomCoach(String prenomCoach) {
        this.prenomCoach = prenomCoach;
    }
    public String getMailCoach() {
        return this.mailCoach;
    }
    
    public void setMailCoach(String mailCoach) {
        this.mailCoach = mailCoach;
    }
    public Set<Communiquer> getCommuniquers() {
        return this.communiquers;
    }
    
    public void setCommuniquers(Set<Communiquer> communiquers) {
        this.communiquers = communiquers;
    }
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }




}


