package metier;
// Generated 20 f�vr. 2018 21:49:57 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Communiquer generated by hbm2java
 */
public class Communiquer  implements java.io.Serializable {


     private CommuniquerId id;
     private Client client;
     private Coach coach;
     private Piecejointe piecejointe;
     private String messageComm;
     private Boolean messageUrgence;

    public Communiquer() {
    }

	
    public Communiquer(CommuniquerId id, Client client, Coach coach, Piecejointe piecejointe) {
        this.id = id;
        this.client = client;
        this.coach = coach;
        this.piecejointe = piecejointe;
    }
    public Communiquer(CommuniquerId id, Client client, Coach coach, Piecejointe piecejointe, String messageComm, Boolean messageUrgence) {
       this.id = id;
       this.client = client;
       this.coach = coach;
       this.piecejointe = piecejointe;
       this.messageComm = messageComm;
       this.messageUrgence = messageUrgence;
    }
   
    public CommuniquerId getId() {
        return this.id;
    }
    
    public void setId(CommuniquerId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Coach getCoach() {
        return this.coach;
    }
    
    public void setCoach(Coach coach) {
        this.coach = coach;
    }
    public Piecejointe getPiecejointe() {
        return this.piecejointe;
    }
    
    public void setPiecejointe(Piecejointe piecejointe) {
        this.piecejointe = piecejointe;
    }
    public String getMessageComm() {
        return this.messageComm;
    }
    
    public void setMessageComm(String messageComm) {
        this.messageComm = messageComm;
    }
    public Boolean getMessageUrgence() {
        return this.messageUrgence;
    }
    
    public void setMessageUrgence(Boolean messageUrgence) {
        this.messageUrgence = messageUrgence;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + Objects.hashCode(this.getId());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Communiquer other = (Communiquer) obj;
        if (!Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        return true;
    }




}


