package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1



/**
 * ComposerId generated by hbm2java
 */
public class ComposerId  implements java.io.Serializable {


     private int idExercice;
     private int idOccSeance;
     private int idSeance;
     private int ordre;

    public ComposerId() {
    }

    public ComposerId(int idExercice, int idOccSeance, int idSeance, int ordre) {
       this.idExercice = idExercice;
       this.idOccSeance = idOccSeance;
       this.idSeance = idSeance;
       this.ordre = ordre;
    }
   
    public int getIdExercice() {
        return this.idExercice;
    }
    
    public void setIdExercice(int idExercice) {
        this.idExercice = idExercice;
    }
    public int getIdOccSeance() {
        return this.idOccSeance;
    }
    
    public void setIdOccSeance(int idOccSeance) {
        this.idOccSeance = idOccSeance;
    }
    public int getIdSeance() {
        return this.idSeance;
    }
    
    public void setIdSeance(int idSeance) {
        this.idSeance = idSeance;
    }
    public int getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(int ordre) {
        this.ordre = ordre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComposerId) ) return false;
		 ComposerId castOther = ( ComposerId ) other; 
         
		 return (this.getIdExercice()==castOther.getIdExercice())
 && (this.getIdOccSeance()==castOther.getIdOccSeance())
 && (this.getIdSeance()==castOther.getIdSeance())
 && (this.getOrdre()==castOther.getOrdre());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdExercice();
         result = 37 * result + this.getIdOccSeance();
         result = 37 * result + this.getIdSeance();
         result = 37 * result + this.getOrdre();
         return result;
   }   


}


