package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1



/**
 * Composer generated by hbm2java
 */
public class Composer  implements java.io.Serializable {


     private ComposerId id;
     private Exercice exercice;
     private Occseance occseance;
     private Seance seance;
     private Integer nbRepetitionExercice;
     private Integer nbSerieExercice;
     private String noteClientExercice;
     private String commentaireClientExercice;
     private Integer nbMaximumRepetition;
     private Integer tempsMaximum;
     private Boolean estDefaut;

    public Composer() {
    }

	
    public Composer(ComposerId id, Exercice exercice, Occseance occseance, Seance seance) {
        this.id = id;
        this.exercice = exercice;
        this.occseance = occseance;
        this.seance = seance;
    }
    public Composer(ComposerId id, Exercice exercice, Occseance occseance, Seance seance, Integer nbRepetitionExercice, Integer nbSerieExercice, String noteClientExercice, String commentaireClientExercice, Integer nbMaximumRepetition, Integer tempsMaximum, Boolean estDefaut) {
       this.id = id;
       this.exercice = exercice;
       this.occseance = occseance;
       this.seance = seance;
       this.nbRepetitionExercice = nbRepetitionExercice;
       this.nbSerieExercice = nbSerieExercice;
       this.noteClientExercice = noteClientExercice;
       this.commentaireClientExercice = commentaireClientExercice;
       this.nbMaximumRepetition = nbMaximumRepetition;
       this.tempsMaximum = tempsMaximum;
       this.estDefaut = estDefaut;
    }
   
    public ComposerId getId() {
        return this.id;
    }
    
    public void setId(ComposerId id) {
        this.id = id;
    }
    public Exercice getExercice() {
        return this.exercice;
    }
    
    public void setExercice(Exercice exercice) {
        this.exercice = exercice;
    }
    public Occseance getOccseance() {
        return this.occseance;
    }
    
    public void setOccseance(Occseance occseance) {
        this.occseance = occseance;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Integer getNbRepetitionExercice() {
        return this.nbRepetitionExercice;
    }
    
    public void setNbRepetitionExercice(Integer nbRepetitionExercice) {
        this.nbRepetitionExercice = nbRepetitionExercice;
    }
    public Integer getNbSerieExercice() {
        return this.nbSerieExercice;
    }
    
    public void setNbSerieExercice(Integer nbSerieExercice) {
        this.nbSerieExercice = nbSerieExercice;
    }
    public String getNoteClientExercice() {
        return this.noteClientExercice;
    }
    
    public void setNoteClientExercice(String noteClientExercice) {
        this.noteClientExercice = noteClientExercice;
    }
    public String getCommentaireClientExercice() {
        return this.commentaireClientExercice;
    }
    
    public void setCommentaireClientExercice(String commentaireClientExercice) {
        this.commentaireClientExercice = commentaireClientExercice;
    }
    public Integer getNbMaximumRepetition() {
        return this.nbMaximumRepetition;
    }
    
    public void setNbMaximumRepetition(Integer nbMaximumRepetition) {
        this.nbMaximumRepetition = nbMaximumRepetition;
    }
    public Integer getTempsMaximum() {
        return this.tempsMaximum;
    }
    
    public void setTempsMaximum(Integer tempsMaximum) {
        this.tempsMaximum = tempsMaximum;
    }
    public Boolean getEstDefaut() {
        return this.estDefaut;
    }
    
    public void setEstDefaut(Boolean estDefaut) {
        this.estDefaut = estDefaut;
    }




}


