package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1



/**
 * ConstituerId generated by hbm2java
 */
public class ConstituerId  implements java.io.Serializable {


     private int ordreSeance;
     private int idSeance;
     private int idSequence;
     private int numeroSemaine;
     private int annee;

    public ConstituerId() {
    }

    public ConstituerId(int ordreSeance, int idSeance, int idSequence, int numeroSemaine, int annee) {
       this.ordreSeance = ordreSeance;
       this.idSeance = idSeance;
       this.idSequence = idSequence;
       this.numeroSemaine = numeroSemaine;
       this.annee = annee;
    }
   
    public int getOrdreSeance() {
        return this.ordreSeance;
    }
    
    public void setOrdreSeance(int ordreSeance) {
        this.ordreSeance = ordreSeance;
    }
    public int getIdSeance() {
        return this.idSeance;
    }
    
    public void setIdSeance(int idSeance) {
        this.idSeance = idSeance;
    }
    public int getIdSequence() {
        return this.idSequence;
    }
    
    public void setIdSequence(int idSequence) {
        this.idSequence = idSequence;
    }
    public int getNumeroSemaine() {
        return this.numeroSemaine;
    }
    
    public void setNumeroSemaine(int numeroSemaine) {
        this.numeroSemaine = numeroSemaine;
    }
    public int getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(int annee) {
        this.annee = annee;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConstituerId) ) return false;
		 ConstituerId castOther = ( ConstituerId ) other; 
         
		 return (this.getOrdreSeance()==castOther.getOrdreSeance())
 && (this.getIdSeance()==castOther.getIdSeance())
 && (this.getIdSequence()==castOther.getIdSequence())
 && (this.getNumeroSemaine()==castOther.getNumeroSemaine())
 && (this.getAnnee()==castOther.getAnnee());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrdreSeance();
         result = 37 * result + this.getIdSeance();
         result = 37 * result + this.getIdSequence();
         result = 37 * result + this.getNumeroSemaine();
         result = 37 * result + this.getAnnee();
         return result;
   }   


}


