package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exercice generated by hbm2java
 */
public class Exercice  implements java.io.Serializable {


     private Integer idExercice;
     private Categorieexercice categorieexercice;
     private String libelleExercice;
     private String niveauExercice;
     private String descriptifExercice;
     private String photoExercice;
     private String videoExercice;
     private String recommandationExercice;
     private Set<Composer> composers = new HashSet<Composer>(0);
     private Set<Objectif> objectifs = new HashSet<Objectif>(0);

    public Exercice() {
    }

    public Exercice(Categorieexercice categorieexercice, String libelleExercice, String niveauExercice, String descriptifExercice, String photoExercice, String videoExercice, String recommandationExercice, Set<Composer> composers, Set<Objectif> objectifs) {
       this.categorieexercice = categorieexercice;
       this.libelleExercice = libelleExercice;
       this.niveauExercice = niveauExercice;
       this.descriptifExercice = descriptifExercice;
       this.photoExercice = photoExercice;
       this.videoExercice = videoExercice;
       this.recommandationExercice = recommandationExercice;
       this.composers = composers;
       this.objectifs = objectifs;
    }
   
    public Integer getIdExercice() {
        return this.idExercice;
    }
    
    public void setIdExercice(Integer idExercice) {
        this.idExercice = idExercice;
    }
    public Categorieexercice getCategorieexercice() {
        return this.categorieexercice;
    }
    
    public void setCategorieexercice(Categorieexercice categorieexercice) {
        this.categorieexercice = categorieexercice;
    }
    public String getLibelleExercice() {
        return this.libelleExercice;
    }
    
    public void setLibelleExercice(String libelleExercice) {
        this.libelleExercice = libelleExercice;
    }
    public String getNiveauExercice() {
        return this.niveauExercice;
    }
    
    public void setNiveauExercice(String niveauExercice) {
        this.niveauExercice = niveauExercice;
    }
    public String getDescriptifExercice() {
        return this.descriptifExercice;
    }
    
    public void setDescriptifExercice(String descriptifExercice) {
        this.descriptifExercice = descriptifExercice;
    }
    public String getPhotoExercice() {
        return this.photoExercice;
    }
    
    public void setPhotoExercice(String photoExercice) {
        this.photoExercice = photoExercice;
    }
    public String getVideoExercice() {
        return this.videoExercice;
    }
    
    public void setVideoExercice(String videoExercice) {
        this.videoExercice = videoExercice;
    }
    public String getRecommandationExercice() {
        return this.recommandationExercice;
    }
    
    public void setRecommandationExercice(String recommandationExercice) {
        this.recommandationExercice = recommandationExercice;
    }
    public Set<Composer> getComposers() {
        return this.composers;
    }
    
    public void setComposers(Set<Composer> composers) {
        this.composers = composers;
    }
    public Set<Objectif> getObjectifs() {
        return this.objectifs;
    }
    
    public void setObjectifs(Set<Objectif> objectifs) {
        this.objectifs = objectifs;
    }




}


