package metier;
// Generated 20 f�vr. 2018 21:49:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Mesure generated by hbm2java
 */
public class Mesure  implements java.io.Serializable {


     private Integer idMesure;
     private String libelleMesure;
     private Set<Mesurer> mesurers = new HashSet<Mesurer>(0);

    public Mesure() {
    }

    public Mesure(String libelleMesure, Set<Mesurer> mesurers) {
       this.libelleMesure = libelleMesure;
       this.mesurers = mesurers;
    }
   
    public Integer getIdMesure() {
        return this.idMesure;
    }
    
    public void setIdMesure(Integer idMesure) {
        this.idMesure = idMesure;
    }
    public String getLibelleMesure() {
        return this.libelleMesure;
    }
    
    public void setLibelleMesure(String libelleMesure) {
        this.libelleMesure = libelleMesure;
    }
    public Set<Mesurer> getMesurers() {
        return this.mesurers;
    }
    
    public void setMesurers(Set<Mesurer> mesurers) {
        this.mesurers = mesurers;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 79 * hash + Objects.hashCode(this.getIdMesure());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Mesure other = (Mesure) obj;
        if (!Objects.equals(this.getIdMesure(), other.getIdMesure())) {
            return false;
        }
        return true;
    }




}


