package metier;
// Generated 20 févr. 2018 21:49:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MesurerId generated by hbm2java
 */
public class MesurerId  implements java.io.Serializable {


     private int idClient;
     private Date dateMesure;
     private int idMesure;

    public MesurerId() {
    }

    public MesurerId(int idClient, Date dateMesure, int idMesure) {
       this.idClient = idClient;
       this.dateMesure = dateMesure;
       this.idMesure = idMesure;
    }
   
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }
    public Date getDateMesure() {
        return this.dateMesure;
    }
    
    public void setDateMesure(Date dateMesure) {
        this.dateMesure = dateMesure;
    }
    public int getIdMesure() {
        return this.idMesure;
    }
    
    public void setIdMesure(int idMesure) {
        this.idMesure = idMesure;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MesurerId) ) return false;
		 MesurerId castOther = ( MesurerId ) other; 
         
		 return (this.getIdClient()==castOther.getIdClient())
 && ( (this.getDateMesure()==castOther.getDateMesure()) || ( this.getDateMesure()!=null && castOther.getDateMesure()!=null && this.getDateMesure().equals(castOther.getDateMesure()) ) )
 && (this.getIdMesure()==castOther.getIdMesure());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdClient();
         result = 37 * result + ( getDateMesure() == null ? 0 : this.getDateMesure().hashCode() );
         result = 37 * result + this.getIdMesure();
         return result;
   }   


}


