package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1



/**
 * Mesurer generated by hbm2java
 */
public class Mesurer  implements java.io.Serializable {


     private MesurerId id;
     private Client client;
     private Mesure mesure;
     private Float valeur;

    public Mesurer() {
    }

	
    public Mesurer(MesurerId id, Client client, Mesure mesure) {
        this.id = id;
        this.client = client;
        this.mesure = mesure;
    }
    public Mesurer(MesurerId id, Client client, Mesure mesure, Float valeur) {
       this.id = id;
       this.client = client;
       this.mesure = mesure;
       this.valeur = valeur;
    }
   
    public MesurerId getId() {
        return this.id;
    }
    
    public void setId(MesurerId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Mesure getMesure() {
        return this.mesure;
    }
    
    public void setMesure(Mesure mesure) {
        this.mesure = mesure;
    }
    public Float getValeur() {
        return this.valeur;
    }
    
    public void setValeur(Float valeur) {
        this.valeur = valeur;
    }




}


