package metier;
// Generated 20 f�vr. 2018 21:49:57 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Mesurer generated by hbm2java
 */
public class Mesurer  implements java.io.Serializable {


     private MesurerId id;
     private Client client;
     private Mesure mesure;
     private Float valeur;

    public Mesurer() {
    }

	
    public Mesurer(MesurerId id, Client client, Mesure mesure) {
        this.id = id;
        this.client = client;
        this.mesure = mesure;
    }
    public Mesurer(MesurerId id, Client client, Mesure mesure, Float valeur) {
       this.id = id;
       this.client = client;
       this.mesure = mesure;
       this.valeur = valeur;
    }
   
    public MesurerId getId() {
        return this.id;
    }
    
    public void setId(MesurerId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Mesure getMesure() {
        return this.mesure;
    }
    
    public void setMesure(Mesure mesure) {
        this.mesure = mesure;
    }
    public Float getValeur() {
        return this.valeur;
    }
    
    public void setValeur(Float valeur) {
        this.valeur = valeur;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 83 * hash + Objects.hashCode(this.getId());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Mesurer other = (Mesurer) obj;
        if (!Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        return true;
    }




}


