package metier;
// Generated 20 f�vr. 2018 21:49:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Objectif generated by hbm2java
 */
public class Objectif  implements java.io.Serializable {


     private Integer idObjectif;
     private String libelleObjectif;
     private Set<Exercice> exercices = new HashSet<Exercice>(0);

    public Objectif() {
    }

    public Objectif(String libelleObjectif, Set<Exercice> exercices) {
       this.libelleObjectif = libelleObjectif;
       this.exercices = exercices;
    }
   
    public Integer getIdObjectif() {
        return this.idObjectif;
    }
    
    public void setIdObjectif(Integer idObjectif) {
        this.idObjectif = idObjectif;
    }
    public String getLibelleObjectif() {
        return this.libelleObjectif;
    }
    
    public void setLibelleObjectif(String libelleObjectif) {
        this.libelleObjectif = libelleObjectif;
    }
    public Set<Exercice> getExercices() {
        return this.exercices;
    }
    
    public void setExercices(Set<Exercice> exercices) {
        this.exercices = exercices;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + Objects.hashCode(this.getIdObjectif());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Objectif other = (Objectif) obj;
        if (!Objects.equals(this.getIdObjectif(), other.getIdObjectif())) {
            return false;
        }
        return true;
    }




}


