package metier;
// Generated 20 f�vr. 2018 21:49:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Occseance generated by hbm2java
 */
public class Occseance  implements java.io.Serializable {


     private Integer idOccSeance;
     private Client client;
     private Occseance occseance;
     private Float dureeOccSeance;
     private Boolean statutOccSeance;
     private String etatOccSeance;
     private Integer tourMinimum;
     private Integer tourMaximum;
     private Date dateFin;
     private Date dateDebut;
     private Integer fcRepos;
     private Integer fcAllonge;
     private Integer fcFlexion;
     private Integer fcRecuperation;
     private String commentaireCoach;
     private Set<Composer> composers = new HashSet<Composer>(0);
     private Set<Occseance> occseances = new HashSet<Occseance>(0);

    public Occseance() {
    }

    public Occseance(Client client, Occseance occseance, Float dureeOccSeance, Boolean statutOccSeance, String etatOccSeance, Integer tourMinimum, Integer tourMaximum, Date dateFin, Date dateDebut, Integer fcRepos, Integer fcAllonge, Integer fcFlexion, Integer fcRecuperation, String commentaireCoach, Set<Composer> composers, Set<Occseance> occseances) {
       this.client = client;
       this.occseance = occseance;
       this.dureeOccSeance = dureeOccSeance;
       this.statutOccSeance = statutOccSeance;
       this.etatOccSeance = etatOccSeance;
       this.tourMinimum = tourMinimum;
       this.tourMaximum = tourMaximum;
       this.dateFin = dateFin;
       this.dateDebut = dateDebut;
       this.fcRepos = fcRepos;
       this.fcAllonge = fcAllonge;
       this.fcFlexion = fcFlexion;
       this.fcRecuperation = fcRecuperation;
       this.commentaireCoach = commentaireCoach;
       this.composers = composers;
       this.occseances = occseances;
    }
   
    public Integer getIdOccSeance() {
        return this.idOccSeance;
    }
    
    public void setIdOccSeance(Integer idOccSeance) {
        this.idOccSeance = idOccSeance;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Occseance getOccseance() {
        return this.occseance;
    }
    
    public void setOccseance(Occseance occseance) {
        this.occseance = occseance;
    }
    public Float getDureeOccSeance() {
        return this.dureeOccSeance;
    }
    
    public void setDureeOccSeance(Float dureeOccSeance) {
        this.dureeOccSeance = dureeOccSeance;
    }
    public Boolean getStatutOccSeance() {
        return this.statutOccSeance;
    }
    
    public void setStatutOccSeance(Boolean statutOccSeance) {
        this.statutOccSeance = statutOccSeance;
    }
    public String getEtatOccSeance() {
        return this.etatOccSeance;
    }
    
    public void setEtatOccSeance(String etatOccSeance) {
        this.etatOccSeance = etatOccSeance;
    }
    public Integer getTourMinimum() {
        return this.tourMinimum;
    }
    
    public void setTourMinimum(Integer tourMinimum) {
        this.tourMinimum = tourMinimum;
    }
    public Integer getTourMaximum() {
        return this.tourMaximum;
    }
    
    public void setTourMaximum(Integer tourMaximum) {
        this.tourMaximum = tourMaximum;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public Integer getFcRepos() {
        return this.fcRepos;
    }
    
    public void setFcRepos(Integer fcRepos) {
        this.fcRepos = fcRepos;
    }
    public Integer getFcAllonge() {
        return this.fcAllonge;
    }
    
    public void setFcAllonge(Integer fcAllonge) {
        this.fcAllonge = fcAllonge;
    }
    public Integer getFcFlexion() {
        return this.fcFlexion;
    }
    
    public void setFcFlexion(Integer fcFlexion) {
        this.fcFlexion = fcFlexion;
    }
    public Integer getFcRecuperation() {
        return this.fcRecuperation;
    }
    
    public void setFcRecuperation(Integer fcRecuperation) {
        this.fcRecuperation = fcRecuperation;
    }
    public String getCommentaireCoach() {
        return this.commentaireCoach;
    }
    
    public void setCommentaireCoach(String commentaireCoach) {
        this.commentaireCoach = commentaireCoach;
    }
    public Set<Composer> getComposers() {
        return this.composers;
    }
    
    public void setComposers(Set<Composer> composers) {
        this.composers = composers;
    }
    public Set<Occseance> getOccseances() {
        return this.occseances;
    }
    
    public void setOccseances(Set<Occseance> occseances) {
        this.occseances = occseances;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 59 * hash + Objects.hashCode(this.getIdOccSeance());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Occseance other = (Occseance) obj;
        if (!Objects.equals(this.getIdOccSeance(), other.getIdOccSeance())) {
            return false;
        }
        return true;
    }




}


