package metier;
// Generated 20 f�vr. 2018 21:49:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Occurenceprogramme generated by hbm2java
 */
public class Occurenceprogramme  implements java.io.Serializable {


     private Integer idOccProgramme;
     private Programme programme;
     private String etatOccProgramme;
     private Set<Suivre> suivres = new HashSet<Suivre>(0);

    public Occurenceprogramme() {
    }

    public Occurenceprogramme(Programme programme, String etatOccProgramme, Set<Suivre> suivres) {
       this.programme = programme;
       this.etatOccProgramme = etatOccProgramme;
       this.suivres = suivres;
    }
   
    public Integer getIdOccProgramme() {
        return this.idOccProgramme;
    }
    
    public void setIdOccProgramme(Integer idOccProgramme) {
        this.idOccProgramme = idOccProgramme;
    }
    public Programme getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(Programme programme) {
        this.programme = programme;
    }
    public String getEtatOccProgramme() {
        return this.etatOccProgramme;
    }
    
    public void setEtatOccProgramme(String etatOccProgramme) {
        this.etatOccProgramme = etatOccProgramme;
    }
    public Set<Suivre> getSuivres() {
        return this.suivres;
    }
    
    public void setSuivres(Set<Suivre> suivres) {
        this.suivres = suivres;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + Objects.hashCode(this.getIdOccProgramme());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Occurenceprogramme other = (Occurenceprogramme) obj;
        if (!Objects.equals(this.getIdOccProgramme(), other.getIdOccProgramme())) {
            return false;
        }
        return true;
    }




}


