package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Occurenceprogramme generated by hbm2java
 */
public class Occurenceprogramme  implements java.io.Serializable {


     private Integer idOccProgramme;
     private Programme programme;
     private String etatOccProgramme;
     private Set<Suivre> suivres = new HashSet<Suivre>(0);

    public Occurenceprogramme() {
    }

    public Occurenceprogramme(Programme programme, String etatOccProgramme, Set<Suivre> suivres) {
       this.programme = programme;
       this.etatOccProgramme = etatOccProgramme;
       this.suivres = suivres;
    }
   
    public Integer getIdOccProgramme() {
        return this.idOccProgramme;
    }
    
    public void setIdOccProgramme(Integer idOccProgramme) {
        this.idOccProgramme = idOccProgramme;
    }
    public Programme getProgramme() {
        return this.programme;
    }
    
    public void setProgramme(Programme programme) {
        this.programme = programme;
    }
    public String getEtatOccProgramme() {
        return this.etatOccProgramme;
    }
    
    public void setEtatOccProgramme(String etatOccProgramme) {
        this.etatOccProgramme = etatOccProgramme;
    }
    public Set<Suivre> getSuivres() {
        return this.suivres;
    }
    
    public void setSuivres(Set<Suivre> suivres) {
        this.suivres = suivres;
    }




}


