package metier;
// Generated 20 f�vr. 2018 21:49:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Piecejointe generated by hbm2java
 */
public class Piecejointe  implements java.io.Serializable {


     private Integer idPieceJointe;
     private String nomPieceJointe;
     private Set<Communiquer> communiquers = new HashSet<Communiquer>(0);
     private Set<Client> clients = new HashSet<Client>(0);

    public Piecejointe() {
    }

    public Piecejointe(String nomPieceJointe, Set<Communiquer> communiquers, Set<Client> clients) {
       this.nomPieceJointe = nomPieceJointe;
       this.communiquers = communiquers;
       this.clients = clients;
    }
   
    public Integer getIdPieceJointe() {
        return this.idPieceJointe;
    }
    
    public void setIdPieceJointe(Integer idPieceJointe) {
        this.idPieceJointe = idPieceJointe;
    }
    public String getNomPieceJointe() {
        return this.nomPieceJointe;
    }
    
    public void setNomPieceJointe(String nomPieceJointe) {
        this.nomPieceJointe = nomPieceJointe;
    }
    public Set<Communiquer> getCommuniquers() {
        return this.communiquers;
    }
    
    public void setCommuniquers(Set<Communiquer> communiquers) {
        this.communiquers = communiquers;
    }
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + Objects.hashCode(this.getIdPieceJointe());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Piecejointe other = (Piecejointe) obj;
        if (!Objects.equals(this.getIdPieceJointe(), other.getIdPieceJointe())) {
            return false;
        }
        return true;
    }




}


