package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Piecejointe generated by hbm2java
 */
public class Piecejointe  implements java.io.Serializable {


     private Integer idPieceJointe;
     private String nomPieceJointe;
     private Set<Communiquer> communiquers = new HashSet<Communiquer>(0);
     private Set<Client> clients = new HashSet<Client>(0);

    public Piecejointe() {
    }

    public Piecejointe(String nomPieceJointe, Set<Communiquer> communiquers, Set<Client> clients) {
       this.nomPieceJointe = nomPieceJointe;
       this.communiquers = communiquers;
       this.clients = clients;
    }
   
    public Integer getIdPieceJointe() {
        return this.idPieceJointe;
    }
    
    public void setIdPieceJointe(Integer idPieceJointe) {
        this.idPieceJointe = idPieceJointe;
    }
    public String getNomPieceJointe() {
        return this.nomPieceJointe;
    }
    
    public void setNomPieceJointe(String nomPieceJointe) {
        this.nomPieceJointe = nomPieceJointe;
    }
    public Set<Communiquer> getCommuniquers() {
        return this.communiquers;
    }
    
    public void setCommuniquers(Set<Communiquer> communiquers) {
        this.communiquers = communiquers;
    }
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }




}


