package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profilsportif generated by hbm2java
 */
public class Profilsportif  implements java.io.Serializable {


     private Integer idProfilSportif;
     private String libelleProfilSportif;
     private Set<Client> clients = new HashSet<Client>(0);

    public Profilsportif() {
    }

    public Profilsportif(String libelleProfilSportif, Set<Client> clients) {
       this.libelleProfilSportif = libelleProfilSportif;
       this.clients = clients;
    }
   
    public Integer getIdProfilSportif() {
        return this.idProfilSportif;
    }
    
    public void setIdProfilSportif(Integer idProfilSportif) {
        this.idProfilSportif = idProfilSportif;
    }
    public String getLibelleProfilSportif() {
        return this.libelleProfilSportif;
    }
    
    public void setLibelleProfilSportif(String libelleProfilSportif) {
        this.libelleProfilSportif = libelleProfilSportif;
    }
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }




}


