package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Programme generated by hbm2java
 */
public class Programme  implements java.io.Serializable {


     private Integer idProgramme;
     private String libelleProgramme;
     private Set<Occurenceprogramme> occurenceprogrammes = new HashSet<Occurenceprogramme>(0);

    public Programme() {
    }

    public Programme(String libelleProgramme, Set<Occurenceprogramme> occurenceprogrammes) {
       this.libelleProgramme = libelleProgramme;
       this.occurenceprogrammes = occurenceprogrammes;
    }
   
    public Integer getIdProgramme() {
        return this.idProgramme;
    }
    
    public void setIdProgramme(Integer idProgramme) {
        this.idProgramme = idProgramme;
    }
    public String getLibelleProgramme() {
        return this.libelleProgramme;
    }
    
    public void setLibelleProgramme(String libelleProgramme) {
        this.libelleProgramme = libelleProgramme;
    }
    public Set<Occurenceprogramme> getOccurenceprogrammes() {
        return this.occurenceprogrammes;
    }
    
    public void setOccurenceprogrammes(Set<Occurenceprogramme> occurenceprogrammes) {
        this.occurenceprogrammes = occurenceprogrammes;
    }




}


