package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seance generated by hbm2java
 */
public class Seance  implements java.io.Serializable {


     private Integer idSeance;
     private String libelleSeance;
     private String profilSeance;
     private Set<Composer> composers = new HashSet<Composer>(0);
     private Set<Constituer> constituers = new HashSet<Constituer>(0);

    public Seance() {
    }

	
    public Seance(String libelleSeance) {
        this.libelleSeance = libelleSeance;
    }
    public Seance(String libelleSeance, String profilSeance, Set<Composer> composers, Set<Constituer> constituers) {
       this.libelleSeance = libelleSeance;
       this.profilSeance = profilSeance;
       this.composers = composers;
       this.constituers = constituers;
    }
   
    public Integer getIdSeance() {
        return this.idSeance;
    }
    
    public void setIdSeance(Integer idSeance) {
        this.idSeance = idSeance;
    }
    public String getLibelleSeance() {
        return this.libelleSeance;
    }
    
    public void setLibelleSeance(String libelleSeance) {
        this.libelleSeance = libelleSeance;
    }
    public String getProfilSeance() {
        return this.profilSeance;
    }
    
    public void setProfilSeance(String profilSeance) {
        this.profilSeance = profilSeance;
    }
    public Set<Composer> getComposers() {
        return this.composers;
    }
    
    public void setComposers(Set<Composer> composers) {
        this.composers = composers;
    }
    public Set<Constituer> getConstituers() {
        return this.constituers;
    }
    
    public void setConstituers(Set<Constituer> constituers) {
        this.constituers = constituers;
    }




}


