package metier;
// Generated 20 f�vr. 2018 21:49:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Sequence generated by hbm2java
 */
public class Sequence  implements java.io.Serializable {


     private Integer idSequence;
     private String libelleSequence;
     private Integer nbRepetitionSequence;
     private Integer idOccProgramme;
     private int ordreSequence;
     private Set<Constituer> constituers = new HashSet<Constituer>(0);

    public Sequence() {
    }

	
    public Sequence(int ordreSequence) {
        this.ordreSequence = ordreSequence;
    }
    
    public Sequence(String libelleSequence, Integer nbRepetitionSequence, Integer idOccProgramme, int ordreSequence, Set<Constituer> constituers) {
       this.libelleSequence = libelleSequence;
       this.nbRepetitionSequence = nbRepetitionSequence;
       this.idOccProgramme = idOccProgramme;
       this.ordreSequence = ordreSequence;
       this.constituers = constituers;
    }
    
    public Sequence (String Libelle, Integer nbRepet, int OrdreSeq){
        this.libelleSequence = Libelle;
        this.nbRepetitionSequence = nbRepet;
        this.ordreSequence = OrdreSeq;
    }
   
    public Integer getIdSequence() {
        return this.idSequence;
    }
    
    public void setIdSequence(Integer idSequence) {
        this.idSequence = idSequence;
    }
    public String getLibelleSequence() {
        return this.libelleSequence;
    }
    
    public void setLibelleSequence(String libelleSequence) {
        this.libelleSequence = libelleSequence;
    }
    public Integer getNbRepetitionSequence() {
        return this.nbRepetitionSequence;
    }
    
    public void setNbRepetitionSequence(Integer nbRepetitionSequence) {
        this.nbRepetitionSequence = nbRepetitionSequence;
    }
    public Integer getIdOccProgramme() {
        return this.idOccProgramme;
    }
    
    public void setIdOccProgramme(Integer idOccProgramme) {
        this.idOccProgramme = idOccProgramme;
    }
    public int getOrdreSequence() {
        return this.ordreSequence;
    }
    
    public void setOrdreSequence(int ordreSequence) {
        this.ordreSequence = ordreSequence;
    }
    public Set<Constituer> getConstituers() {
        return this.constituers;
    }
    
    public void setConstituers(Set<Constituer> constituers) {
        this.constituers = constituers;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 59 * hash + Objects.hashCode(this.getIdSequence());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Sequence other = (Sequence) obj;
        if (!Objects.equals(this.getIdSequence(), other.getIdSequence())) {
            return false;
        }
        return true;
    }




}


