package metier;
// Generated 20 f�vr. 2018 21:49:57 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Suivre generated by hbm2java
 */
public class Suivre  implements java.io.Serializable {


     private SuivreId id;
     private Client client;
     private Occurenceprogramme occurenceprogramme;
     private Integer semaineFin;

    public Suivre() {
    }

	
    public Suivre(SuivreId id, Client client, Occurenceprogramme occurenceprogramme) {
        this.id = id;
        this.client = client;
        this.occurenceprogramme = occurenceprogramme;
    }
    public Suivre(SuivreId id, Client client, Occurenceprogramme occurenceprogramme, Integer semaineFin) {
       this.id = id;
       this.client = client;
       this.occurenceprogramme = occurenceprogramme;
       this.semaineFin = semaineFin;
    }
   
    public SuivreId getId() {
        return this.id;
    }
    
    public void setId(SuivreId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Occurenceprogramme getOccurenceprogramme() {
        return this.occurenceprogramme;
    }
    
    public void setOccurenceprogramme(Occurenceprogramme occurenceprogramme) {
        this.occurenceprogramme = occurenceprogramme;
    }
    public Integer getSemaineFin() {
        return this.semaineFin;
    }
    
    public void setSemaineFin(Integer semaineFin) {
        this.semaineFin = semaineFin;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + Objects.hashCode(this.getId());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Suivre other = (Suivre) obj;
        if (!Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        return true;
    }




}


