package metier;
// Generated 20 févr. 2018 16:23:10 by Hibernate Tools 4.3.1



/**
 * Suivre generated by hbm2java
 */
public class Suivre  implements java.io.Serializable {


     private SuivreId id;
     private Client client;
     private Occurenceprogramme occurenceprogramme;
     private Integer semaineFin;

    public Suivre() {
    }

	
    public Suivre(SuivreId id, Client client, Occurenceprogramme occurenceprogramme) {
        this.id = id;
        this.client = client;
        this.occurenceprogramme = occurenceprogramme;
    }
    public Suivre(SuivreId id, Client client, Occurenceprogramme occurenceprogramme, Integer semaineFin) {
       this.id = id;
       this.client = client;
       this.occurenceprogramme = occurenceprogramme;
       this.semaineFin = semaineFin;
    }
   
    public SuivreId getId() {
        return this.id;
    }
    
    public void setId(SuivreId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Occurenceprogramme getOccurenceprogramme() {
        return this.occurenceprogramme;
    }
    
    public void setOccurenceprogramme(Occurenceprogramme occurenceprogramme) {
        this.occurenceprogramme = occurenceprogramme;
    }
    public Integer getSemaineFin() {
        return this.semaineFin;
    }
    
    public void setSemaineFin(Integer semaineFin) {
        this.semaineFin = semaineFin;
    }




}


