package metier;
// Generated 20 f�vr. 2018 16:23:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private Integer idUtilisateur;
     private String nomUtilisateur;
     private String prenomUtilisateur;
     private String mailUtilisateur;
     private String mpdUtilisateur;
     private Set<Role> roles = new HashSet<Role>(0);

    public Utilisateur() {
    }

    public Utilisateur(String nomUtilisateur, String prenomUtilisateur, String mailUtilisateur, String mpdUtilisateur) {
       this.nomUtilisateur = nomUtilisateur;
       this.prenomUtilisateur = prenomUtilisateur;
       this.mailUtilisateur = mailUtilisateur;
       this.mpdUtilisateur = mpdUtilisateur;
    }    
    
    public Utilisateur(String nomUtilisateur, String prenomUtilisateur, String mailUtilisateur, String mpdUtilisateur, Set<Role> roles) {
       this.nomUtilisateur = nomUtilisateur;
       this.prenomUtilisateur = prenomUtilisateur;
       this.mailUtilisateur = mailUtilisateur;
       this.mpdUtilisateur = mpdUtilisateur;
       this.roles = roles;
    }
   
    public Integer getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(Integer idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }
    public String getNomUtilisateur() {
        return this.nomUtilisateur;
    }
    
    public void setNomUtilisateur(String nomUtilisateur) {
        this.nomUtilisateur = nomUtilisateur;
    }
    public String getPrenomUtilisateur() {
        return this.prenomUtilisateur;
    }
    
    public void setPrenomUtilisateur(String prenomUtilisateur) {
        this.prenomUtilisateur = prenomUtilisateur;
    }
    public String getMailUtilisateur() {
        return this.mailUtilisateur;
    }
    
    public void setMailUtilisateur(String mailUtilisateur) {
        this.mailUtilisateur = mailUtilisateur;
    }
    public String getMpdUtilisateur() {
        return this.mpdUtilisateur;
    }
    
    public void setMpdUtilisateur(String mpdUtilisateur) {
        this.mpdUtilisateur = mpdUtilisateur;
    }
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }




}


